# Generated by Django 5.2.1 on 2025-05-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_paint_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_2fa_verified',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='otp_secret',
        ),
        migrations.AddField(
            model_name='customuser',
            name='telegram_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
