# Generated by Django 5.2.1 on 2025-05-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_paint_app', '0002_remove_customuser_is_2fa_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('moderator', 'Модератор'), ('user', 'Пользователь')], default='user', max_length=10),
        ),
    ]
