# Generated by Django 5.2.1 on 2025-05-28 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_paint_app', '0003_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(blank=True, max_length=10, unique=True)),
                ('project', models.CharField(max_length=100)),
                ('device', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('date_received', models.DateField()),
                ('deadline', models.DateField()),
            ],
        ),
    ]
