# Generated by Django 5.2.1 on 2025-06-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_paint_app', '0004_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.TextField(blank=True, default='Не принят', null=True),
        ),
    ]
