# Generated by Django 5.2.1 on 2025-06-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_paint_app', '0005_request_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='request_id',
        ),
        migrations.AlterField(
            model_name='request',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('новый', 'Новый'), ('в работе', 'В работе'), ('завершён', 'Завершён')], default='новый', max_length=20),
        ),
    ]
