# Generated by Django 5.2.1 on 2025-06-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_paint_app', '0006_remove_request_request_id_alter_request_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='request_id',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.TextField(blank=True, default='Не принят', null=True),
        ),
    ]
