# Generated by Django 5.2.1 on 2025-06-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_paint_app', '0008_atm'),
    ]

    operations = [
        migrations.AddField(
            model_name='atm',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='atm',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='atm_photos/'),
        ),
    ]
