# Generated by Django 5.2.1 on 2025-06-09 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_paint_app', '0009_atm_comment_atm_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atm',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='atm',
            name='image',
        ),
        migrations.CreateModel(
            name='ATMImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='atm_photos/')),
                ('atm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Backend_paint_app.atm')),
            ],
        ),
    ]
