# Generated by Django 5.2.1 on 2025-06-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_paint_app', '0010_remove_atm_comment_remove_atm_image_atmimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='atmimage',
            name='photo_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
