# Generated by Django 5.2.1 on 2025-06-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_paint_app', '0011_atmimage_photo_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atmimage',
            name='photo_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
