# Generated by Django 5.2.1 on 2025-06-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_paint_app', '0012_alter_atmimage_photo_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='atmimage',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
