# Generated by Django 5.2.1 on 2025-06-11 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_paint_app', '0015_alter_pushsubscription_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PushSubscription',
        ),
    ]
