# Generated by Django 5.2.1 on 2025-06-16 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_paint_app', '0016_delete_pushsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, verbose_name='Серийный номер')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Срок выполнения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
        ),
        migrations.CreateModel(
            name='ReclamationPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='reclamations/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reclamation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='Backend_paint_app.reclamation')),
            ],
        ),
    ]
