# Generated by Django 5.2.1 on 2025-06-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_paint_app', '0018_reclamation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
