# Generated by Django 5.2.1 on 2025-06-16 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_paint_app', '0019_reclamation_remarks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reclamation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Рекламация', 'verbose_name_plural': 'Рекламации'},
        ),
        migrations.AddField(
            model_name='reclamation',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reclamations', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AddField(
            model_name='reclamation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_reclamations', to=settings.AUTH_USER_MODEL, verbose_name='Обработал'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'В ожидании'), ('in_progress', 'В работе'), ('resolved', 'Исправлено'), ('rejected', 'Отклонено')], default='pending', max_length=20, null=True, verbose_name='Статус'),
        ),
    ]
