# Generated by Django 5.2.1 on 2025-06-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_paint_app', '0020_alter_reclamation_options_reclamation_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('admin_paint', 'Админ_пок'), ('moderator', 'Модератор'), ('user', 'Пользователь')], default='user', max_length=15),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'В ожидании'), ('in_progress', 'В работе'), ('in_check', 'На проверке'), ('resolved', 'Исправлено'), ('rejected', 'Отклонено')], default='pending', max_length=20, null=True, verbose_name='Статус'),
        ),
    ]
