# Generated by Django 5.2.1 on 2025-06-17 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_paint_app', '0021_alter_customuser_role_alter_reclamation_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atm',
            options={'verbose_name': 'Банкоматы', 'verbose_name_plural': 'Банкоматы'},
        ),
        migrations.AlterModelOptions(
            name='atmimage',
            options={'verbose_name': 'Фото неисправностей', 'verbose_name_plural': 'Фото неисправностей'},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name': 'Заявки', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AddField(
            model_name='reclamation',
            name='remarks_corrections',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий исправления'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('admin_paint', 'Админ_пок'), ('admin_pp', 'Админ_пп'), ('moderator', 'Модератор'), ('user', 'Пользователь')], default='user', max_length=15),
        ),
        migrations.AlterField(
            model_name='reclamation',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий рекламации'),
        ),
    ]
