# Generated by Django 5.2.1 on 2025-06-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_paint_app', '0022_alter_atm_options_alter_atmimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='remarks_remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий к рекламации'),
        ),
    ]
