# Generated by Django 5.2.1 on 2025-06-17 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_paint_app', '0023_reclamation_remarks_remarks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reclamation',
            old_name='remarks_remarks',
            new_name='comment_remarks',
        ),
    ]
